---
- hosts: test
  gather_facts: yes
  name: configure audit rules
  tasks: 




  - name: Ensure syslog-ng default file permissions configured
    shell: ls /etc/syslog-ng/syslog-ng.conf
    register: file_exist
    ignore_errors: yes
  - copy:
      src: /etc/syslog-ng/syslog-ng.conf
      dest: /usr/share/cis
      force: no
      remote_src: yes
    when: file_exist.stdout != ""
  - shell: grep ^options /etc/syslog-ng/syslog-ng.conf
    register: syslog_def_check
    ignore_errors: yes
  - lineinfile:
       path: /etc/syslog-ng/syslog-ng.conf
       line: options { chain_hostnames(off); flush_lines(0); perm(0640); stats_freq(3600); threaded(yes); };
       insertafter: yes
       state: present
    when: file_exist.stdout != "" and syslog_def_check.stdout == ""

  - name: Ensure syslog-ng is configured to send logs to a remote log host
    blockinfile:
       path: /etc/syslog-ng/syslog-ng.conf
       content: |
          destination logserver { tcp("logfile.example.com" port(514)); };
          log { source(src); destination(logserver); };
       insertafter: yes
       state: present
    when: file_exist.stdout != "" and syslog_def_check.stdout == ""
    notify:
       - name: reload the syslog-ng configuration


  - name: Ensure remote syslog-ng messages are only accepted on designated log hosts
    blockinfile:
       path: /etc/syslog-ng/syslog-ng.conf
       content: |
           source net{ tcp(); };
           destination remote { file("/var/log/remote/${FULLHOST}-log"); };
           log { source(net); destination(remote); };
       insertafter: yes
       state: present
    when: file_exist.stdout != "" and syslog_def_check.stdout == ""
    notify:
       - name: reload the syslog-ng configuration


  - name: Ensure permissions on all logfiles are configured
    shell: find /var/log -type f -exec chmod g-wx,o-rwx {} +

  handlers:
   - name: reload the syslog-ng configuration
     shell: pkill -HUP rsyslogd


