---
- hosts: test
  tasks:

  - name: Ensure ipv6 is disabled, no ipv6 entry
    shell: grep '^\s*kernel.*ipv6.disable=1.*' /boot/grub/grub.conf
    ignore_errors: yes
    register: ipv6_status


  - name: ensure /etc/hosts.allow existence
    copy:
      src: /etc/hosts.allow
      dest: /usr/share/cis
      force: no
  - file:
      path: /etc/hosts.allow
      owner: root
      group: root
      mode: '644'

  - name: ensure /etc/hosts.deny existence
    copy:
      src: /etc/hosts.deny
      dest: /usr/share/cis
      force: no
  - file:
     path: /etc/hosts.deny
     owner: root
     group: root
     mode: '644'

  #- name: Enure /etc/hosts.deny is configured
  #  lineinfile:
  #   path: /etc/hosts.deny
  #   line: "ALL: ALL"
  #   state: present

  
  - name: disabling ipv6
    lineinfile:
     path: /boot/grub/grub.conf
     backrefs: yes
     regexp: '^(\s*kernel.*)'
     line: '\1 ipv6.disable=1'
    when: ipv6_status.stdout == ""

  - name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled
    shell: grep '^\s*kernel.*audit=1.*' /boot/grub/grub.conf
    ignore_errors: yes
    register: prior_status

  - name: adding audit=1
    lineinfile: 
     path: /boot/grub/grub.conf
     backup: True
     backrefs: True
     state: present
     regexp: '^(\s*kernel.*)'
     line: '\1 audit=1'
    when: prior_status.stdout == ""

  - name: copy /etc/securetty
    copy:
     src: /etc/securetty
     dest: /usr/share/cis/securetty
     remote_src: yes
     force: no

  - name: remove root access from securetty
    shell: "> /etc/securetty"

