---
- hosts: os
  tasks:
  - debug:
      msg: RollBacking The dataCenter From CIS Deployment


  - name: ROLLING BACK
    pause: 
      seconds: 5
 
- name: Installing the Required Libraries and Packages
  import_playbook: pkg-rollback.yml

- name: Roll-backing configuration files
  import_playbook: confiuration-rollback.yml

- name: Configuring SSH
  import_playbook: ssh_config-rollback.yml

- name: RollBacking Modules' configuration
  import_playbook: modules-rollback.yml

- name: RollBacking Filesystems Hardening process
  import_playbook: filesystems-rollback.yml

- name: RollBacking service setting
  import_playbook: service-rollback.yml

- name: RollBacking ports setting
  import_playbook: port-rollback.yml

- name: Restoring audit
  import_playbook: audit-rollback.yml

- name: Restoring authentication
  import_playbook: authentication-rollback.yml

- name: RollBacking Firewall setting
  import_playbook: firewall-rollback.yml

